### PR TITLE
relax node and iojs restrictions

### PR DESCRIPTION
**Pull request by nmccready**

### CODE REVIEW

**Comment by nmccready** [comment]
CLA was signed

**Comment by nmccready** [comment]
There is no travis.yml nor a npm test script so I have no clue why its running or failing.

**Comment by Dignifiedquire** [comment]
You can ignore travis, it's not properly setup as you've seen. 
Could you please change the relaxation to what is currently present in `master` of the main karma. That's tested and running fine without warnings on `0.8`, `0.10`, `0.12` and `iojs@2`.

**Comment by nmccready** [comment]
ok will do

**Pull request closed without merging**
