### PR TITLE
chore(release): v2.0.0

### PR DESCRIPTION
**Pull request by rogeriopvl**
Here's a much needed release :)

Latest release was on Jun 26, 2016. I don't have NPM permissions to publish, so that's the only step needed after merging this PR.

Edit: and also push the tag

cc @dignifiedquire @johnjbarton

### CODE REVIEW

**Comment by johnjbarton** [comment]
How did you create the change log? My attempt fails:
```sh
$grunt release:major
Running "release:major" (release) task
Warning: Task "changelog" not found. Use --force to continue.
```

**Comment by rogeriopvl** [comment]
@johnjbarton I used the `conventional-changelog-cli` directly. Just noticed that `grunt-conventional-changelog` broke when updating to latest version. I'm going to fix it ASAP.

**Comment by rogeriopvl** [comment]
@johnjbarton fixed in 32b14d2a

**Comment by rogeriopvl** [comment]
@johnjbarton I noticed you already commited the release. I'm going to close this. But what's stopping  2.0.0 from being published to NPM?

**Comment by johnjbarton** [comment]
I don't have permission to npm publish but I am working on it.

**Comment by johnjbarton** [comment]
Ok finally sorted it, please check the release.

**Comment by rogeriopvl** [comment]
Great! Thanks @johnjbarton

**Pull request closed without merging**
